

AVAILABLE_PARSERS = ['riksdagen', 'arbetsformedlingen', 'bra', 'msb']
RIKSDAGEN = AVAILABLE_PARSERS[0]
ARBETSFORMEDLINGEN = AVAILABLE_PARSERS[1]
BRA = AVAILABLE_PARSERS[2]
MSB = AVAILABLE_PARSERS[3]

ELASTICSEARCH_ENDPOINT = 'http://localhost:9200'
